name: Bootstrap and markup

on: workflow_dispatch

jobs:
  bootstrap_and_markup:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: Bootstrap
      run: ./scripts/bootstrap.sh --exit-on-error
