name: Bootstrap and markup

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  bootstrap_and_markup:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: Bootstrap
      run: ./scripts/bootstrap_all.sh --exit-on-error
